### ISSUE TITLE
Crash on getUserStatus

### ISSUE THREAD

**Issue by RomainLambert-nuglif** [didomi/didomi-ios-sdk-spm#9]
Hello,

We can see a lot of crashes on firebase caused by the Didomi SDK, the origin seems to be this line:

`Didomi.shared.getUserStatus().purposes.global`

Do you have any idea of how to avoid this kind of crash?

The end of the stack trace is : 
```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1688 objc_retain_x8 + 16
1  libswiftCore.dylib             0x404620 objcRetainAndReturn(void*) + 32
2  Didomi                         0x9a46c objectdestroy.11Tm + 25664
3  Didomi                         0x993dc objectdestroy.11Tm + 21424
4  Didomi                         0x15d688 objectdestroy.2Tm + 67464
5  Didomi                         0x15dae0 objectdestroy.2Tm + 68576
6  LPRI                           0x2562e0 specialized UserConsentManager.hasConsent(for:) + 121 (UserConsentManager.swift:121)
```

The line 121 of our class is:
`let globalPurposes = Didomi.shared.getUserStatus().purposes.global`

We can't find a way to reproduce it but we have 56 users on the last seven days who have encountered the issue.
Do you have any idea? Thank you!

**Comment by felipe-saez** [comment]
Hello Romain,

I've noticed that this issue doesn't appear to be specific to the Swift Package of the Didomi iOS SDK. Instead, it seems to be related to the iOS SDK itself. To ensure your request is prioritised and receives better visibility, I recommend reaching out directly to the Didomi Tech Support team at support@didomi.io.

By taking a quick look at the crash report you are sharing, I notice that the lines that involve the Didomi library don't seem to be fully symbolicated. When reaching out to the support team, please try to include a crash report that is fully symbolicated so we can have a better idea of where the issue is coming from.

Kind regards,

Felipe
